version: "3.7"
networks:
    internal:
        driver: "bridge"
services:
    python:
        build: 
            context: ./api
            target: ${APP_ENV:-development}
        volumes:
            - ./api:/var/www/html
        networks: 
            - internal
        ports:
            - "${APP_PORT:-5000}:5000"      
        restart: always
