"""empty message

Revision ID: 48edb12b8a68
Revises: 65061617d77d
Create Date: 2020-11-04 08:20:40.667238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48edb12b8a68'
down_revision = '65061617d77d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'updated_at')
    op.drop_column('user', 'created_at')
    # ### end Alembic commands ###
